package com.vibely.app.ui.navigation

object Routes {
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val FORGOT_PASSWORD = "forgot_password"
    const val HOME = "home"
    const val DISCOVER = "discover"
    const val MATCH = "match"
    const val CALL = "call"
    const val CHAT = "chat"
    const val PROFILE = "profile"
    const val WALLET = "wallet"
    const val GIFTS = "gifts"
    const val FAVORITES = "favorites"
    const val HISTORY = "history"
    const val NOTIFICATIONS = "notifications"
    const val SETTINGS = "settings"
    const val ADMIN_DASHBOARD = "admin_dashboard"
    const val ADMIN_USERS = "admin_users"
    const val ADMIN_REPORTS = "admin_reports"
    const val ADMIN_MODERATION = "admin_moderation"
    const val ADMIN_ANALYTICS = "admin_analytics"
    const val ADMIN_SETTINGS = "admin_settings"
}
